services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5


  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: always


  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - ./server/.env
    volumes:
      - ./server/logs:/app/logs
    restart: always


  client:
    build: ./client
    container_name: client
    ports:
      - "8081:8081"
      - "19000-19006:19000-19006"
    depends_on:
      - server
    volumes:
      - ./client/logs:/app/logs
      - ./client:/app
      - /app/node_modules
    restart: always
    command: ["npx", "expo", "start", "--tunnel"]
    

volumes:
  mongodb_data:
