version: "3.8"

services:
  server:
    build: .
    container_name: server
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    volumes:
      - ./logs:/app/logs
      - ./server/database/json:/app/server/database/json  # Persist JSON data
    restart: always

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always

  jenkins:
    build: ./jenkins  
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  
    restart: always

volumes:
  grafana_data:
  jenkins_home:
